config/routes.rb
Rails.application.routes.draw do

  get 'cart/index'

  devise_for :users

  root 'product_items#index'

  resources :products

  resources :product_items

  post 'cart/add' => 'cart#add_cart'
  get 'cart/clear' => 'cart#clear_cart'

end

app/models/cart.rb
# To change this license header, choose License Headers in Project Properties. To change this template file, choose
# Tools | Templates and open the template in the editor.

class Cart
  include ActiveModel::Model

  attr_accessor :cart_items

  def initialize
    @cart_items ||= []
  end

  # カートインスタンスに商品と個数を追加します
  def add_item(sku, quantity)
    cart_item = @cart_items.find{|a| a.sku.eql? sku}
    unless cart_item
      cart_item = CartItem.new
      cart_item.sku = sku
      @cart_items << cart_item
    end
    cart_item.quantity += quantity.to_i

    cart_item
  end

  # カートインスタンスに商品と個数を変更します
  def edit_item(sku, quantity)
    cart_item = @cart_items.find{|a| a.sku.eql? sku}
    if cart_item
      cart_item = CartItem.new
      cart_item.quantity = quantity
    end
  end

  # カートインスタンスに商品と個数を追加します
  def remove_item(sku)
    @cart_items.delete_if{|a|
      a.sku.eql? sku
    }
  end
end

app/models/cart_item.rb
# To change this license header, choose License Headers in Project Properties. To change this template file, choose
# Tools | Templates and open the template in the editor.

class CartItem
  include ActiveModel::Model

  attr_accessor :cart
  attr_accessor :sku
  attr_accessor :product_item_id
  attr_accessor :quantity

  def initialize
    @quantity = 0
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :cart_items
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  def selectable_quantity
    10
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def get_cart
    @cart = session[:cart] || Cart.new
    @cart
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :authenticate_user!

  before_action :get_cart

  def index
  end

  # カートに商品を追加する
  def add_cart
    cart_item = @cart.add_item(add_cart_params[:sku], add_cart_params[:quantity])
    redirect_to cart_index_path

    flash[:cart_item] = cart_item
    session[:cart] = @cart
  end

  # カートに商品を追加する
  def edit_cart
    cart_item = @cart.edit_item(edit_cart_params[:sku], edit_cart_params[:quantity])
    redirect_to cart_index_path

    flash[:cart_item] = cart_item
    session[:cart] = @cart
  end

  # カート内の商品を削除する
  def remove_cart
    cart_item = @cart.add_item(add_cart_params[:sku], add_cart_params[:quantity])
    redirect_to cart_index_path

    flash[:cart_item] = cart_item
    session[:cart] = @cart
  end

  def clear_cart
    session[:cart] = nil

    redirect_to product_items_path
  end

  private

    # カートに追加する時に必要なパラメータ
    def add_cart_params
      params.require(:cart_item).permit(:sku, :quantity)
    end

    # カートに追加する時に必要なパラメータ
    def edit_cart_params
      params.require(:cart_item).permit(:sku, :quantity)
    end

    # カートから商品を削除する時に必要なパラメータ
    def remove_cart_params
      params.require(:cart_item).permit(:sku)
    end
end

app/controllers/product_items_controller.rb
class ProductItemsController < ApplicationController
  before_action :set_product_item, only: [:show, :edit, :update, :destroy]

  # GET /product_items
  # GET /product_items.json
  def index
    @product_items = ProductItem.all
  end

  # GET /product_items/1
  # GET /product_items/1.json
  def show
  end

  # GET /product_items/new
  def new
    @product_item = ProductItem.new
  end

  # GET /product_items/1/edit
  def edit
  end

  # POST /product_items
  # POST /product_items.json
  def create
    @product_item = ProductItem.new(product_item_params)

    respond_to do |format|
      if @product_item.save
        format.html { redirect_to @product_item, notice: 'Product item was successfully created.' }
        format.json { render :show, status: :created, location: @product_item }
      else
        format.html { render :new }
        format.json { render json: @product_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_items/1
  # PATCH/PUT /product_items/1.json
  def update
    respond_to do |format|
      if @product_item.update(product_item_params)
        format.html { redirect_to @product_item, notice: 'Product item was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_item }
      else
        format.html { render :edit }
        format.json { render json: @product_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_items/1
  # DELETE /product_items/1.json
  def destroy
    @product_item.destroy
    respond_to do |format|
      format.html { redirect_to product_items_url, notice: 'Product item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_item
      @product_item = ProductItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_item_params
      params.require(:product_item).permit(:product_id, :sku, :sales_price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/product_items_helper.rb
module ProductItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.slim
div カート

- if flash[:cart_item]
  div
    | 追加された商品
    = flash[:cart_item]

table style="border: 1px;" ng-controller="CartController"
  thead
    tr
      th &nbsp
      th sku
      th 個数
      th 価格

  tbody ng-repeat="cart in carts"
    tr
      td
        img ng-src="{{cart.thumbnail_url}}"
      td
        |{{::cart.sku}}
      td
        input[type="number" name="quantity" ng-model="cart.quantity" min="0" required style="width: 45px;"]
      td
        |{{cart.sales_price * cart.quantity || 0}}

div
  = link_to '商品ページ', product_items_path

div
  = link_to "カート削除", cart_clear_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CartExample
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    header
      div.header-left
        = link_to "CartExample", root_path
      div.header-right
        |ようこそ
        - if user_signed_in?
          = current_user.email
        - else
          |ゲス

      div.header-right
        = link_to 'カート', cart_index_path

      br clear="both"

    = yield

app/views/product_items/_form.html.slim
= form_for @product_item do |f|
  - if @product_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product_item.errors.count, "error")} prohibited this product_item from being saved:"
      ul
        - @product_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :sku
    = f.text_field :sku
  .field
    = f.label :sales_price
    = f.text_field :sales_price
  .actions = f.submit 'Save'

app/views/product_items/edit.html.slim
h1 Editing product_item

== render 'form'

= link_to 'Show', @product_item
'|
= link_to 'Back', product_items_path

app/views/product_items/index.html.slim
h1 Listing product_items

table
  thead
    tr
      th Product
      th Sku
      th Sales price
      th
      th
      th

  tbody
    - @product_items.each do |product_item|
      tr
        td = product_item.product_id
        td = product_item.sku
        td = product_item.sales_price
        td = link_to 'Show', product_item
        td = link_to 'Edit', edit_product_item_path(product_item)
        td = link_to 'Destroy', product_item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product item', new_product_item_path

app/views/product_items/new.html.slim
h1 New product_item

== render 'form'

= link_to 'Back', product_items_path

app/views/product_items/show.html.slim
p#notice = notice

div#container
  div#image_detail
    = image_tag @product_item.image_url

  div
    strong Product:
    div#product_id = @product_item.product_id
  div
    strong Sku:
    div#sku = @product_item.sku
  p
    strong Sales price:
    div#price = @product_item.sales_price

  = form_tag cart_add_path, :method => :post, :id => 'add_cart_form' do
    div#hidden
      = hidden_field_tag "cart_item[sku]", @product_item.sku
    p
      個数&nbsp:&nbsp

    div#quantity
      /- if !@product_item.available?
        /品切れ中です
      /- elsif @product_item.selectable_quantity > 0

      = select_tag "cart_item[quantity]", options_for_select((1..@product_item.selectable_quantity).collect {|i| [i, i] })


    div#submit
      /- if @product_item.order_acceptable?
      = submit_tag "カートに入れる"
      /- else
        /在庫がありません

  = link_to 'Edit', edit_product_item_path(@product_item)
  '|
  = link_to 'Back', product_items_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit 'Save'

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/index.html.slim
h1 Listing products

table
  thead
    tr
      th Code
      th Name
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.code
        td = product.name
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Code:
  = @product.code
p
  strong Name:
  = @product.name

= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path